pull_request_rules:
  - name: automatic merge for PRs from bots
    conditions:
      - or:
          - author = dependabot[bot]
          - author = mirakc-ci[bot]
      - check-success = build / build
      - check-success = cross-build / cross-build (armhf)
      - check-success = cross-build / cross-build (arm64)
    actions:
      merge:
        method: merge
