jobs:
  coverage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache for external projects
        uses: actions/cache@v2
        with:
          path: build/vendor
          key: ${{ runner.os }}-coverage-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-coverage-
      - name: Cache for grcov
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-grcov
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends autoconf automake cmake dos2unix g++ libtool make ninja-build pkg-config
      - name: Generate project files
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug -D MIRAKC_ARIB_TEST=ON -D MIRAKC_ARIB_COVERAGE=ON
      - name: Build vendor libraries
        run: |
          ninja -C build vendor
      - name: Build
        run: |
          ninja -C build
      - name: Run test
        run: |
          ninja -C build test
          ninja -C build cli-tests
      - name: Install grcov
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov
      - name: Generate coverage data
        run: >-
          grcov build --branch --llvm --ignore-not-existing -s . -p ..
          --ignore 'test/*'
          -t lcov -o lcov.info
      - name: Update to codecov.io
        uses: codecov/codecov-action@v2
        with:
         files: lcov.info
