name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  linux-build:
  macos-build:
  arm-linux-build:
  coverage:
    needs:
      - linux-build
