name: ARM-Linux

on: [push]

jobs:
  build:
    strategy:
      matrix:
        arch:
          - armel
          - armhf
          - arm64
        include:
          - arch: armel
            host-triple: arm-linux-gnueabi
          - arch: armhf
            host-triple: arm-linux-gnueabihf
          - arch: arm64
            host-triple: aarch64-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends autoconf automake cmake dos2unix g++-8-${{ matrix.host-triple }} libtool make ninja-build pkg-config
          sudo update-alternatives --install /usr/bin/${{ matrix.host-triple}}-gcc ${{ matrix.host-triple}}-gcc /usr/bin/${{ matrix.host-triple}}-gcc-8 80
          sudo update-alternatives --install /usr/bin/${{ matrix.host-triple}}-g++ ${{ matrix.host-triple}}-g++ /usr/bin/${{ matrix.host-triple}}-g++-8 80
      - uses: actions/checkout@v1
      - name: Generate project files
        run: |
          cmake -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE=${{ github.GITHUB_WORKSPACE }}/toolchain.cmake.d/debian-${{ matrix.host-triple }}.cmake .
      - name: Build vendor libraries
        run: |
          ninja vendor
      - name: Build
        run: |
          ninja
