name: daily

on:
  schedule:
    - cron: '5 5 * * *'  # 05:05 (UTC)

env:
  UPDATE_DEPS_TITLE: 'build(deps): update dependencies'

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          # Fetch all history for all branches and tags
          # so that ./scripts/update-deps works properly.
          fetch-depth: 0
      - name: git config
        run: |
          # https://github.com/orgs/community/discussions/26560#discussioncomment-3252339
          BOT_NAME='github-actions[bot]'
          BOT_ID="$(curl https://api.github.com/users/$(echo -n github-actions[bot] | jq -sRr '@uri') -sG | jq -r '.id')"
          git config user.name "$BOT_NAME"
          git config user.email "$BOT_ID+$BOT_NAME@users.noreply.github.com"
      - name: Make a pull-request to update dependencies
        run: |
          ./scripts/update-deps
          if git diff --quiet -- vendor
          then
            echo "Not changed"
          else
            BRANCH="update-deps-$(date '+%Y%m%d')"
            git checkout -b $BRANCH
            git add vendor
            git commit -m "$UPDATE_DEPS_TITLE"
            git push -u origin $BRANCH
            gh pr create -t "$UPDATE_DEPS_TITLE" -b '' -l dependencies
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
