name: macOS

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Install deps
        run: |
          brew install autoconf automake gnu-sed grep dos2unix libtool make ninja pkg-config
      - uses: actions/checkout@v1
      - name: Generate project files
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D MIRAKC_ARIB_TEST=ON
      - name: Build vendor libraries
        run: |
          ninja -C build vendor
      - name: Build
        run: |
          ninja -C build
      - name: Show help
        run: |
          build/bin/mirakc-arib -h
      - name: Run tests
        run: |
          ninja -C build test
        env:
          MIRAKC_ARIB_CI: YES
