name: Weekly

on:
  schedule:
    #- cron: '19 19 * * 4'  # 19:19 (UTC), Thursday
    - cron: '* * * * *'  # for testing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      - name: git config
        run: |
          # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          TAG="$(git describe --tags --abbrev=0)"
          if git diff --quiet "$TAG"
          then
            echo "Not changed, skip to create new release"
          else
            ./scripts/release patch
            git push
            git push --tags
          fi
