name: weekly

on:
  schedule:
    - cron: '19 19 * * 4'  # 19:19 (UTC), Thursday

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: raven-actions/bot-details@v1
        id: bot-details
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          # Fetch all history for all tags and branches
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${{ steps.bot-details.outputs.name }}"
          git config user.email "${{ steps.bot-details.outputs.email }}"
      - run: |
          TAG="$(git describe --tags --abbrev=0)"
          if git diff --quiet "$TAG"
          then
            echo "Not changed, skip to create new release"
          else
            ./scripts/release patch
            git push
            git push --tags
          fi
